const encoded = [
  {
    groupId: 783,

    areaId: "0",
    departmentId: "688",
    directionId: "0",
    mediaTypeId: "0",
    mediaId: "676",
    resellingId: "18842",
    serviceTypeId: "124",
    formatTypeId: "0",
    formatId: "0",
    unitId: "82226",
    platformId: "0",
    budgetId: null,
    adPlatformId: "1026",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 784,

    areaId: "0",
    departmentId: "688",
    directionId: "0",
    mediaTypeId: "0",
    mediaId: "676",
    resellingId: "18842",
    serviceTypeId: "124",
    formatTypeId: "0",
    formatId: "0",
    unitId: "82226",
    platformId: "0",
    budgetId: null,
    adPlatformId: "1026",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 793,

    areaId: "0",
    departmentId: "688",
    directionId: "18858",
    mediaTypeId: "111",
    mediaId: "676",
    resellingId: "18842",
    serviceTypeId: "124",
    formatTypeId: "15152",
    formatId: "82193",
    unitId: "82226",
    platformId: "0",
    budgetId: null,
    adPlatformId: "1026",
    service: null,
    formatSize: "Не применимо",
    ca: null,
    mpmId: null,
  },
];

const decoded = [
  {
    groupId: 783,

    areaId: "",
    departmentId: "Маркетинг",
    directionId: "",
    mediaTypeId: "",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 784,

    areaId: "",
    departmentId: "Маркетинг",
    directionId: "",
    mediaTypeId: "",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 793,

    areaId: "",
    departmentId: "Маркетинг",
    directionId: "СММ - 3",
    mediaTypeId: "СММ",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "Баннеры",
    formatId: "Баннеры",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: "Не применимо",
    ca: null,
    mpmId: null,
  },
];

export { encoded, decoded };
